[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet SocialMediaAPI.dll"
restartPolicyType = "ON_FAILURE"

[deploy.envs]
ASPNETCORE_ENVIRONMENT = "Production"
JWT_SECRET = "${JWT_SECRET}"
JWT_ISSUER = "https://socialmediaapi-production-74e1.up.railway.app"
JWT_AUDIENCE = "https://socialmediaapi-production-74e1.up.railway.app"
