[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet SocialMediaAPI.dll"
restartPolicyType = "ON_FAILURE"

[deploy.envs]
ASPNETCORE_ENVIRONMENT = "Production"
POSTGRES_HOST = "${POSTGRES_HOST}"
POSTGRES_PORT = "${POSTGRES_PORT}"
POSTGRES_DB = "${POSTGRES_DB}"
POSTGRES_USER = "${POSTGRES_USER}"
POSTGRES_PASSWORD = "${POSTGRES_PASSWORD}"
JWT_SECRET = "${JWT_SECRET}"
JWT_ISSUER = "${JWT_ISSUER}"
JWT_AUDIENCE = "${JWT_AUDIENCE}"
JWT_EXPIRATION = "${JWT_EXPIRATION}"
EMAIL_PASSWORD = "${EMAIL_PASSWORD}"
EMAIL_FROM = "${EMAIL_FROM}"
EMAIL_HOST = "${EMAIL_HOST}"
EMAIL_PORT = "${EMAIL_PORT}"